package Navigator;

public enum ActionTypes {

    OPEN_LANDING,
    OPEN_LOGIN,
    OPEN_REGISTER,
    OPEN_FORGOT,
    OPEN_ADMIN_HOME,
    OPEN_MOVIE,
    OPEN_CINEMA,
    OPEN_CINEMA_MOVIE,
    OPEN_SETTING,
    OPEN_TOP_5_EDITOR,
    OPEN_USER_HOME,
    OPEN_SEARCH_FILTER_VIEW,
    OPEN_MOVIE_DETAILS,
    OPEN_BOOKING,
    OPEN_BOOKING_HISTORY,
    OPEN_TOP_5,
    EXIT,
    
}
